### PR TITLE
Add UniFFI derives to ValidationMode and custom_type for Network

### PR DESCRIPTION
**Pull request by xdustinface**
## Summary
- Adds `#[cfg_attr(feature = "uniffi", derive(uniffi::Enum))]` to `ValidationMode`
- Adds `custom_type!` bridge for `dashcore::Network` to `String` in `bridge/mod.rs`
- First step toward direct UniFFI integration on existing types

Partial progress on #6 — subsequent PRs will add derives to `ClientConfig`, event types, etc.

### CODE REVIEW

**Comment by xdustinface** [comment]
@claude CI fails with syntax error at `dash-spv/src/bridge/mod.rs:12`:

```
error: expected `,`
  --> dash-spv/src/bridge/mod.rs:12:30
   |
12 | uniffi::custom_type!(dashcore::Network, String, {
   |                              ^
```

The `custom_type!` macro with `remote` + closures syntax might not be supported in the UniFFI version used by this project. Check `dash-spv/Cargo.toml` for the UniFFI version and use the correct syntax for that version. The older syntax uses `impl UniffiCustomTypeConverter` trait instead. Fix and push.

**Comment by xdustinface** [comment]
@claude CI still fails. The `custom_type!` closure syntax is not supported in UniFFI 0.28. The error is at `bridge/mod.rs:14`:

```
error: unexpected token
  --> dash-spv/src/bridge/mod.rs:14:37
   |
14 | uniffi::custom_type!(Network, String, {
   |                                     ^
```

In UniFFI 0.28, you must implement the `UniffiCustomTypeConverter` trait instead:

```rust
use dashcore::Network;

impl UniffiCustomTypeConverter for Network {
    type Builtin = String;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        val.parse().map_err(|e| anyhow::anyhow!("Invalid network: {e}"))
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        obj.to_string()
    }
}
```

You also need to declare the type in the UDL file or use `uniffi::custom_type!(Network, String)` (simple form, no closures). Check which approach works for UniFFI 0.28 and fix.

**Comment by xdustinface** [comment]
@claude CI fails with:

```
error[E0405]: cannot find trait `UniffiCustomTypeConverter` in crate `uniffi`
  --> dash-spv/src/bridge/mod.rs:16:14
```

The `UniffiCustomTypeConverter` trait doesn't exist in UniFFI 0.28. In this version, the simple two-argument form `uniffi::custom_type!(Network, String)` should work on its own — it auto-generates conversions using `From`/`Into` traits. Since `dashcore::Network` implements `Display` and `FromStr`, just use:

```rust
use dashcore::Network;
uniffi::custom_type!(Network, String);
```

Remove the `impl UniffiCustomTypeConverter` block entirely and just keep the simple macro call. If `From<Network> for String` and `TryFrom<String> for Network` aren't implemented, you may need to add them. Push the fix.

**Comment by xdustinface** [comment]
@claude Wait — before trying another fix, first upgrade the uniffi dependency to the latest stable version in `dash-spv/Cargo.toml`. The current version (0.28) is old and doesn't support the modern `custom_type\!` syntax. Upgrade `uniffi` to the latest stable (check crates.io for the current version). Then use the modern syntax:

```rust
use dashcore::Network;

uniffi::custom_type\!(Network, String, {
    remote,
    lower: |n| n.to_string(),
    try_lift: |s| s.parse().map_err(Into::into),
});
```

Update both the `uniffi` and `uniffi_macros`/`uniffi_build` dependencies if they exist. Push the fix.

**Comment by xdustinface** [comment]
@claude The CI is still failing because Cargo.lock still pins uniffi to 0.28.3 even though Cargo.toml says 0.29. Run `cargo update -p uniffi` to update the lockfile, then commit and push the updated Cargo.lock. Also: upgrade to the latest stable uniffi (0.31.0), not just 0.29. Update both Cargo.toml and Cargo.lock.

**Comment by xdustinface** [comment]
@claude The UniFFI upgrade to 0.31.0 worked but there is a new error: `String` does not implement `std::error::Error`, so `Into::into` cannot convert it to `anyhow::Error`. In `bridge/mod.rs` line 17, change `s.parse().map_err(Into::into)` to `s.parse().map_err(|e| uniffi::deps::anyhow::anyhow\!(e))`. This wraps the String error into an anyhow error.

**Comment by xdustinface** [comment]
@claude CI still failing. The `anyhow\!` macro needs a type annotation for the error on older Rust (MSRV 1.89). Change line 17 in `bridge/mod.rs` to: `try_lift: |s| s.parse().map_err(|e: String| uniffi::deps::anyhow::anyhow\!(e)),` — add `: String` type annotation to the closure parameter.
